default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: my_secrets_development

test:
  <<: *default
  database: my_secrets_test


production:
  <<: *default
  database: my_secrets_production
  username: rails
  password: <%= ENV['APP_DATABASE_PASSWORD'] %>
