#
# Symmetric Encryption for Ruby
#
---
# For the development and test environments the test symmetric encryption keys
# can be placed directly in the source code.
# And therefore no RSA private key is required
development:   &development_defaults
  key:         1234567890ABCDEF1234567890ABCDEF
  iv:          1234567890ABCDEF
  cipher_name: aes-128-cbc
  encoding:    :base64strict

test:
  <<: *development_defaults

release:
  # Since the key to encrypt and decrypt with must NOT be stored along with the
  # source code, we only hold a RSA key that is used to unlock the file
  # containing the actual symmetric encryption key
  private_rsa_key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpgIBAAKCAQEAtIltZmBmPjco7ez+XQqHNt+y0DZ0t07uOaLD0C00iYKl0h/q
    f3XiyI+JtJ7h7DUJRQSwMiBOimwBAw1hTgRbU3KDeUqOn4yClU2ac5rWHHNzksSK
    SBz3prCMKMhEktKTpu+UFZZFD+oNbjepbocJ+6gyKLq2mArFFnMrI897w6WAhRUZ
    huBppRpr3shFRVG4eOc/7PbpfzeXn13lgo2cXXsm42zv/W5lVB98Z8iPrI7vaCrb
    kw0N7EQds+vqZUBfDCFbpSZbUngXxIpVCJNzdSMob7CQihjsZlLgsC1iPfKQwB1E
    8rT68ybHBKsh8FLxhLZxqvTEtaHuOAZjWtRGNwIDAQABAoIBAQCbdphJh4uj2bYa
    JHHpxu4m970whSQ+0e5cnWfHdZX/MA0BA9DYD7jJgqlPa14bHJSt5Vqg36cildzN
    NxFqsF/AXSUQJn7or4OndBsjn9ruxxBn+20kqiUsWm1nlQVP9ZuGLlqzuCIikScd
    mTsC3bBgEDeZUSd5iBStv2EPxlTKZOAkyCm+zGvGuGKSMdK/8foeq04XtimUjwDL
    1hWkditOFITUMKAptN884X7HZmOtix2RCiVKpEQBHxL19FXkG2a/dcfE0l/tPjJt
    dREksxCsiW5fExLKbAWhgG0bESM4QyP2jJ5HlPn0DC8DVovWqPVCKD67v2is9dl3
    BN1NVonBAoGBAOdgIu30iExjT/tPS1S5I9QK9v3QRZmmNGvptTvPIkJDmM/Zsch7
    ORW52SHCMypgLp5jNL+hy51cJStxGPQkxRIS0Kaikj/4RqbY8DFuh5V/H3Cf0Ej3
    fqKMAYhCjV5bODTs+2/xFtskEXvmkxG/UNOJdi3KRi6X8tRx/kN4RdQXAoGBAMfA
    LqF2gmXnSdnWnkfpQQxgc1LSxjMihx4typY/R7LT8P8xAgWLbh9aLyYCYlz5iF7c
    9mgziAm+b19lq3T5ElMky/tJXFJnwFGsDD1eTcM5+tUAB8EPCAJ5M8DKR7wr0pE8
    OoJ8z3duDawfJNPJXJr+bJDrnjtDb7NwCsyoltLhAoGBANVK44hW91rr5mx2sawd
    rDCqFvzuBWtaM1MTtBW5ogxSAkoBlgmJxpsHo2mie8ZhujganiLWRT0AF+fPL8DJ
    ML6zh5NFpOrBtmfS7sGy8dxXvyT0vm61cRDpXfQ93dKQ5uSrXjLYnkhQHKoKaaNf
    qWQIgWA+6qnDO4CqwUlzU3PrAoGBALlQ2bIgYU+rKT+5NfUfOKMD5Fnlg82y7coY
    z4dew+Trbf1C+U4tkgfyQiWwNpNtSZBAzTXVARORIoBNsaj+3npWfAvwfn9RFAJx
    bJWOpPRHGSd9NLRufo7U5SeqQq0Xtu3ZA6tFobB6YKLb7e2yNYDyI8S7Y3w1zy6Y
    9tvyWKLhAoGBAIKkJJmk2H2Kn69aHX+o4V7L1kKYctiDMrkzM9PehyVDdnrxy99S
    6K4HnIG9qqPgqJtI+5pzam6eQuqQX0/RXiT8LdV0y4X8acWmpjx3AoBlpCzAsEMG
    m7cwn4J9OYxhJl7E04y0saeoLaC9uW44DNhZQDbfc+Q9qa5JhExZ+oQA
    -----END RSA PRIVATE KEY-----


  # List Symmetric Key files in the order of current / latest first
  ciphers:
    -
      # Filename containing Symmetric Encryption Key encrypted using the
      # RSA public key derived from the private key above
      key_filename: /etc/rails/keys/my_secrets_release.key
      iv_filename:  /etc/rails/keys/my_secrets_release.iv
      cipher_name:  aes-256-cbc
      # Base64 encode encrypted data without newlines
      encoding:     :base64strict
      version:      1

production:
  # Since the key to encrypt and decrypt with must NOT be stored along with the
  # source code, we only hold a RSA key that is used to unlock the file
  # containing the actual symmetric encryption key
  private_rsa_key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEowIBAAKCAQEAzmgvzYnhldriQ10a1yEQorLIQoHCI1P/xGyXsZfSBRRoNSBd
    QAyimraBTosM0VqpF4UheMxGMDQKfZtehRtMcJlSzZOHC9H2bAGOMuHobahujE88
    PfB0/7Ws8+HXKSNY6Byd7Rih5DWI3JzW6XEIs1TvcgxRSzVme31KypHJAn2CvGli
    L9ajSqgY8AskEEf7Ge3KCo+6IKqSjzm7goW3QzBPyTSJc8+aYgaIWVzJydeWE2Wu
    e24JN0yPT30mKk21cSshnmtkMBcBWnWaslH+KJjSCkrNmnsRy8c0gsAcfUNi0z9W
    juchNKSoAYDPDw/NhVyQyZoX1Uo+obTWEKH59wIDAQABAoIBAECF80OWca2N0iNq
    zIQpsvCZYN7hf1XZ4V9+7uC2bBHocjcBWgU2rfIdUUjDUQt1Atz2YiNIADz7V7gy
    RJbplLiyRV88WgAI77aNue0QD7+P4pb8AgH+1CRHn7xRghg7E4TjxT6j75/OWG1W
    nhw1mJmu2HdXgGY5WEMMRMAUWLjtARpeu6r4XAFimzf5pcd45Ug6hQ68MOWGRqtf
    ESYVh6Dgp4kfcfKyk8omR2mBD0yaRwnr4QeDgJUqE8DuQusbEuoqUysDPIcvz+pK
    pVFZfuPXo3tGc4ltp2xbZ3Y8ZZGZgH8UCnPNhQTlsEsEKejCSyiW1SNFXZYZfSnk
    /YUn4GkCgYEA+q90lYSV8ZAO56omSNVvTfqpCUVujAD08QKkaqoXMf31jZZV6VPt
    1vSmee0uz1vAwGXQ5jJOOiRikpXGBBuME0A+mktnPqFWH6vyugF6pqL7SE6rB1nX
    TszvP85mv3XQSny5dqU5XorBZIXdyq8PxSTUDMfcQa8C5l5SAK+igU0CgYEA0shr
    Ui1SBrDIGAlw+VsG5qnWD/CWLqosKcHLGnmBdIiXKMqbAp01HcZYDVNeo5n3jMNT
    JJYw9t1MkSmAgOuuU9CdyfKBsnESY9LKtUF04pH3kNGuDzQ91f0ldOcVYGcqfmIj
    I6dzpR5Wzyn1gJiUCH2yysgEegZzfSiH5AJzRlMCgYA0tL0LTqQD9OjdVk3UVGOh
    fokZtOpoLy9QmOCeuIJF9YIyMaCAfS/tWOTDj9WerUjaas3ACGWgHdRHw4utg2kx
    BvnikOX1KhCkeg9/gh4aePviGQAmfIIjRD0tKiU6LfgMISsRQe3M7dl5XBfkrGfh
    aDvZMBAkEzrF2qDdGhBNpQKBgQCHbFDXeVqsBcRo/RfifUNPy2pGz3IOBTNemK3f
    EpXDw0Yq5RD2ev53ZMmJtjilr/RGMfAnH3/R+5iH4zw2mDVmkC/wYahGdzMzg2jN
    T4LDVrjSCIVmK1BXPc9k7lrjlyTMEk01SQ6Z1YY8j162AlGJqwjGFAAcTizBCttT
    +OcLFQKBgE1SFFLidEN5AgVhqsIf5cGzKLG/VzJHwNeDx1X+LQnuprww+c2PTXVq
    i2IytrVtij63qej6QeLnwbwnnDRTPvwnNyMdGJf55tR9ooGqs8HoJgmYbfVvJdDZ
    WReX+ON9RTXRXD6vXzoIZngwMUzC+rcl1BFVpefBklqLgsX2T1gl
    -----END RSA PRIVATE KEY-----


  # List Symmetric Key files in the order of current / latest first
  ciphers:
    -
      # Filename containing Symmetric Encryption Key encrypted using the
      # RSA public key derived from the private key above
      key_filename: /etc/rails/keys/my_secrets_production.key
      iv_filename:  /etc/rails/keys/my_secrets_production.iv
      cipher_name:  aes-256-cbc
      # Base64 encode encrypted data without newlines
      encoding:     :base64strict
      version:      1
