#
# Symmetric Encryption for Ruby
#
---
# For the development and test environments the test symmetric encryption keys
# can be placed directly in the source code.
# And therefore no RSA private key is required
development:   &development_defaults
  key:         1234567890ABCDEF1234567890ABCDEF
  iv:          1234567890ABCDEF
  cipher_name: aes-128-cbc
  encoding:    :base64strict

test:
  <<: *development_defaults

release:
  # Since the key to encrypt and decrypt with must NOT be stored along with the
  # source code, we only hold a RSA key that is used to unlock the file
  # containing the actual symmetric encryption key
  private_rsa_key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEowIBAAKCAQEApijA1xJVc6BqKcKQNfkOHs7/8uzrpsre5ftDMtn1bJewHiRq
    VCzvawu6FDKhRISelI0aVBrttYQ8jnBl/eY3ndIEuc7s0Cf0uIxMiamlKRfHS1k9
    AfK6Bg3t7ZwQ8b5bENJUoqNB7GuPNwk2I83xPdPKCdh1zzbIrsP0JnIQ3WB0nEx3
    VnwZ89S/fh/7Z62zCNt3ODSm1oj0UrOmdvqSBfJla6rP8AAI2VPE/Ji+pLm4+S7O
    Za5UfUZRJ21FteMNgLhmIkksMgrumHvt8qEQo8Dc2ZAsuGLaHJX0Gpr6RcQf6giv
    0nXL9Rx+7CWiGEqjWZmTpf3pi9rgiFx2CNxnVQIDAQABAoIBAD6hd+bZq0oVOk8Z
    XoBpq2/jeMiZk03ghFpN9otxargPCTyjX0zxTyGbXv2EBBOupZO7CCSRre5QtP6/
    0UH+CBK9+jgLjmn71ZvGjocJYg72PpHhRkS4uHPVxkxdGmn05aCWl35iaVPzSx1k
    pHqkgv1aGnrRk76SmNx/UkU3k7HNsPmivLPj8IZmUMH71w3ehy4C+phsbLQ8o0Pr
    ce0sTbFzVqZW0xN1AVDlzf9+lIqyE/NL+O7/jDUFcAO7MuKVU6Ep4ZxMRqCc+mvr
    pfbkeSXPTil+7/cCUEqYK5b2WS8OIGQo4zeZeGxABBKCB15xHTOhqyyAvXMIOok0
    MHVf5YECgYEA2+DVwjbZNuDtsF7dPrTC3GLb7rqfvwDJosInvZhE4YFsOXo24Dae
    0mKach8+svY36kBnT7GMLgQMceUTIUTjOGaq8OzzRu9bSPqincEIaO+hzNztllYy
    7HJORc2kj3Leb/HTpcSvCvFIrHI3QOJsQ1HbeQ0B7KHY5nUkeSudL7UCgYEAwXS3
    u4gm6KVLJ54OvA80h7JWyMd1yKqM4vFnNygpPVg2CwM12MGuBCGRp58YMrIoqEVQ
    c5Lvc6mYKmvNZ6YBJXZvNybz5HFlki/SrptBC39ZAL6po9M2/i9WbPhefhWshRLb
    tJA9qPxch256mAwRt7m9o7scZ32fjW8fI/gC3SECgYBqIEsMQoz0//u5dRA0g+rJ
    lK2yvED+X9Lyy+OCj0wvy9gApgx2i+Z8hTsmeg45Mr4qQoua24ddbnbTQk3JcQZ6
    4pL/Vl7VjhHxV4fFvLXicEcYKkpClbheh41gA7G5yyexwHb3O8eA8JSzJy2kE6VN
    mOTluHGFVVjrYv8HvRVRQQKBgHocyr09PBIuBDqFspdSob3l/JHQFbEMttGpv5U5
    bI6kV7ir1hl0Z/uDlQVRj1ywyKku15Gcdjl0G/DrC0UZrC+RirItjFXunkagmURO
    C8jOIcgukbYvZM8d4lf2ju7Xj4aQWM6pHcLFSULTod7H/4cRX3syaMOKsGP+eJGj
    w2sBAoGBAJP2hgABiFZif5Lo30kKErmN19W2jYbdzs4QrCMugfn3SQj7a6CAAoZp
    sf17asY6AU9WlLSi32IuCXNfnRhOSZq34RkeJkoIy/v9ebt4mx05lfyiPbVDMLlO
    9jjwvzeKMiKAgaXXdc0D99DHOeuTXzt4e1eW0UIBk9Ne5xsq6Oe6
    -----END RSA PRIVATE KEY-----


  # List Symmetric Key files in the order of current / latest first
  ciphers:
    -
      # Filename containing Symmetric Encryption Key encrypted using the
      # RSA public key derived from the private key above
      key_filename: /home/rails/config/my_secrets_release.key
      iv_filename:  /home/rails/config/my_secrets_release.iv
      cipher_name:  aes-256-cbc
      # Base64 encode encrypted data without newlines
      encoding:     :base64strict
      version:      1

production:
  # Since the key to encrypt and decrypt with must NOT be stored along with the
  # source code, we only hold a RSA key that is used to unlock the file
  # containing the actual symmetric encryption key
  private_rsa_key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpAIBAAKCAQEApBk3Q4+WOVbsV8PM7ClmFC+grd44+6derCncJmI35feNfGA5
    FWy3cPaoHdiLmV3xq/cyk7v0OuDHH2ryWn9mqhMl4AQqZrXT3cMFpshmPO8KQ7LX
    2LiWP2wmX94t5LfoJ6BJ4Hp8bYR2USAXbBmMX0IgVnwVooOWFnpSegf0PBiWJ9tU
    LFdAwA+DJs0aMV5RDTw48PQ5NjrmtIeCjqhOTC4jw6xh4iq6/C/yHCeXznm4j9fW
    9RyvEGKWxI6F5I7nfWxBcIEVvt382PoZsTL2sBsdO/zr90og3PQJu3kJRrQxG4CK
    +mk9y8+YZYPewXcsiZ87LiEWQRVoWeMRbX1bzQIDAQABAoIBACJbKSfa8w+0NC03
    0DqNfFKzmgds5C9D3l1bMj1TCPL7vkKQ/sKOjWV4LsB46tlEQunHCm7Fxh9hmi7o
    vC7YR41KDv70wE/at63RO+isQkN1pIeB9RDprINAyFP/90nQeyl4tJ7r5gsj1YWs
    m1rFio8TECQrPHhW5mB0Ybos2iSOh0aUZMXwXGWN8KxfkoS38gISdZ9YI6QqSAmF
    qVET21XTv2XM/Af/V6k6Yyq30aWb1ch/QHTgTgZxbDotEGuBAlRI8e1CA0pbNQw4
    BsicO3KYp7g6rSB93kp4b/V+0vhtvV7GPXW6t1ls3lmN2sGeaF4ORfKEpqFLhgnE
    5LJLXz0CgYEA2FI+AchvYgzqjTw13opjIWwG1XRWl4xyD9yKAYcJAU6286XLOLPR
    IZzhE0atk5bmWyElelOqSZVl3xQNKu/kzbj/Ep6cpMaOIjS9gmhLR/RFSxLJRQXm
    T0BX8sSHKsD2y+CPvZIi2nQ+vDu9oQTuB1EsJruqY7mKJC1dIcMS6/MCgYEAwjLC
    VPCsoEEtifB7YRx1gosgwlOhLTwK2IbMXPNzQuI0k40XBz5LkzRlFY3xpEpt7j74
    WNwEbkXXmF73aLbhoOq+c36WbIXIX8rbPGReXK5c0inBDQin7D+WnXMKQ7wdABjJ
    NOt9dq/xSU1GnisdqNwCFv0KaAMltQcigGN/ST8CgYB4B0o4mwqSkTAkJeCOFqNi
    jBpOnjrd5CP2ARziNBcfDpodH0VftQa5a97HX1Q4rGYs8ntlIL9ADRF1ch7MUEfY
    jmmZ30BzfWioOjNdBJmg1z0LpuTe06MzHjSuk7WcV22ZOoUHXurP4+hbcZqKmb2p
    ebTR2Rd2NiEcab9fWGpLWQKBgQC3OP7i9yRYGsalc5Bk4l34ad3hmtfh/tlYy227
    cTJZc2UZpa+JdPwHChMpUAAh+ttXQnA8HnHLvPeZ2lfho1Kj6XcBLvkrsNmJj7Jj
    e2sQVK5c12o+KuGMY75uFSElITHXaotD878vIPctKsyq5JEaRWFvYRTVZ8rGztF9
    guKQLwKBgQCuuyKGX2wYLa7ZWcST/b9f+z8tlGe/RzPMPcG7Vfn6PgHROOPvPPyF
    56ilmDjqzcB01Z/Oow+aixusP429FpC63ht22Ovsk0NBAvFVIhDX1XeCbFFMW1Qo
    g++6a2E9Y/UXyUFXIgSoC1+ojyOoZMfaffwyDk4JbDOvWEo1wbf/0A==
    -----END RSA PRIVATE KEY-----


  # List Symmetric Key files in the order of current / latest first
  ciphers:
    -
      # Filename containing Symmetric Encryption Key encrypted using the
      # RSA public key derived from the private key above
      key_filename: /home/rails/config/my_secrets_release.key
      iv_filename:  /home/rails/config/my_secrets_release.iv
      cipher_name:  aes-256-cbc
      # Base64 encode encrypted data without newlines
      encoding:     :base64strict
      version:      1
